import createClient from "openapi-fetch";
import type { paths } from "./backend-schema"; // generated by openapi-typescript

const client = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_BACKEND_URL,
});

export default client;
