/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/sign-in/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Google */
        get: operations["login_google_auth_sign_in_google_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in/google/callback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Google */
        get: operations["auth_google_auth_sign_in_google_callback__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User Authentication */
        post: operations["user_authentication_auth_sign_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Detail */
        get: operations["user_detail_user_get"];
        /** Edit User */
        put: operations["edit_user_user_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh Token */
        get: operations["refresh_token_auth_refresh_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All User */
        get: operations["get_all_user_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User By Id */
        get: operations["get_user_by_id_users__user_id__get"];
        /** Edit User By Id */
        put: operations["edit_user_by_id_users__user_id__put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Conversation */
        get: operations["get_all_conversation_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation By Id */
        get: operations["get_conversation_by_id_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/inquire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation By Id With Message */
        get: operations["get_conversation_by_id_with_message_conversations__conversation_id__inquire_get"];
        put?: never;
        /** Create Message By Coverstaion Id */
        post: operations["create_message_by_coverstaion_id_conversations__conversation_id__inquire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Message By Id */
        get: operations["get_message_by_id_messages__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Models */
        get: operations["get_all_models_models_get"];
        put?: never;
        /** Create Model */
        post: operations["create_model_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model By Id */
        get: operations["get_model_by_id_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Feedback To Message */
        put: operations["feedback_to_message_messages__message_id__feedback_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Feedback */
        get: operations["get_all_feedback_feedbacks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback By Id */
        get: operations["get_feedback_by_id_feedbacks__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/{feedback_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Feedback Status */
        put: operations["change_feedback_status_feedbacks__feedback_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedbacks/{feedback_id}/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback Correction */
        get: operations["get_feedback_correction_feedbacks__feedback_id__correction_get"];
        /** Change Feedback Correction */
        put: operations["change_feedback_correction_feedbacks__feedback_id__correction_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConversationDetail */
        ConversationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CreateConversationOrMessageRequest */
        CreateConversationOrMessageRequest: {
            /** Message */
            message: string;
        };
        /** CreateConversationOrMessageResponse */
        CreateConversationOrMessageResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["MessageDetail"][];
        };
        /** CreateModelRequest */
        CreateModelRequest: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** DetailResponse */
        DetailResponse: {
            /** Token */
            token: string;
        };
        /** FeedbackCorrectionDetail */
        FeedbackCorrectionDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Feedback Id
             * Format: uuid
             */
            feedback_id: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FeedbackCorrectionRequst */
        FeedbackCorrectionRequst: {
            /** Content */
            content: string;
        };
        /** FeedbackCorrectionResponse */
        FeedbackCorrectionResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["FeedbackCorrectionDetail"];
        };
        /** FeedbackDetailAdmin */
        FeedbackDetailAdmin: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Score */
            score: number;
            /** Content */
            content: string;
            status: components["schemas"]["FeedbackStatus"];
            correction: components["schemas"]["FeedbackCorrectionDetail"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
        };
        /** FeedbackDetailUser */
        FeedbackDetailUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Message Id
             * Format: uuid
             */
            user_message_id: string;
            /**
             * Bot Message Id
             * Format: uuid
             */
            bot_message_id: string;
            /** Score */
            score: number;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FeedbackMessageResponse */
        FeedbackMessageResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["FeedbackDetailUser"];
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Score */
            score: number;
            /** Content */
            content: string;
        };
        /**
         * FeedbackStatus
         * @enum {string}
         */
        FeedbackStatus: "VALID" | "INVALID" | "IN_REVIEW";
        /** FeedbackStatusRequest */
        FeedbackStatusRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "invalid" | "valid";
            /**
             * Delete
             * @default false
             */
            delete: boolean | null;
            /** Correction */
            correction?: string | null;
        };
        /** GetAllConversationResponse */
        GetAllConversationResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["ConversationDetail"][];
        };
        /** GetAllFeedbackResponse */
        GetAllFeedbackResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["FeedbackDetailAdmin"][];
        };
        /** GetAllModelResponse */
        GetAllModelResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["ModelDetail"][];
        };
        /** GetAllUsersResponse */
        GetAllUsersResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["UserDetail"][];
        };
        /** GetConversationByIDResponse */
        GetConversationByIDResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["ConversationDetail"];
        };
        /** GetConversationByIDWithMessageResponse */
        GetConversationByIDWithMessageResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            /** Data */
            data: components["schemas"]["MessageDetail"][];
        };
        /** GetMessageByIDResponse */
        GetMessageByIDResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["MessageDetail"];
        };
        /** GetModelResponse */
        GetModelResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["ModelDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageDetail */
        MessageDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["RoleEnum"];
            /** Content */
            content: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ModelDetail */
        ModelDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RoleEnum
         * @enum {string}
         */
        RoleEnum: "ASSISTANT" | "SYSTEM" | "USER";
        /** UserAuthRequest */
        UserAuthRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** UserAuthResponse */
        UserAuthResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["DetailResponse"];
        };
        /** UserCreateRequest */
        UserCreateRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** UserDetail */
        UserDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Deleted At */
            deleted_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserDetailResponse */
        UserDetailResponse: {
            /** Code */
            code: number;
            /** Message */
            message: string;
            data: components["schemas"]["UserDetail"];
        };
        /** UserEditRequest */
        UserEditRequest: {
            /** New Username */
            new_username?: string | null;
            /** New Role */
            new_role?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_google_auth_sign_in_google_get: {
        parameters: {
            query: {
                callback_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    auth_google_auth_sign_in_google_callback__get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    user_authentication_auth_sign_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuthResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    user_detail_user_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    edit_user_user_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    refresh_token_auth_refresh_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAuthResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_all_user_users_get: {
        parameters: {
            query?: {
                page?: number | null;
                limit?: number | null;
                search_query?: string | null;
                sort_by?: string | null;
                order?: ("asc" | "desc") | null;
                include_deleted?: boolean;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllUsersResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_user_by_id_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    edit_user_by_id_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    delete_user_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_all_conversation_conversations_get: {
        parameters: {
            query: {
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllConversationResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    create_conversation_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationOrMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateConversationOrMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_conversation_by_id_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConversationByIDResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_conversation_by_id_with_message_conversations__conversation_id__inquire_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConversationByIDWithMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    create_message_by_coverstaion_id_conversations__conversation_id__inquire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationOrMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateConversationOrMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_message_by_id_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMessageByIDResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_all_models_models_get: {
        parameters: {
            query: {
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllModelResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    create_model_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModelResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_model_by_id_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetModelResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    feedback_to_message_messages__message_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_all_feedback_feedbacks_get: {
        parameters: {
            query?: {
                page?: number | null;
                limit?: number | null;
                search_query?: string | null;
                sort_by?: string | null;
                order?: ("asc" | "desc") | null;
                include_deleted?: boolean;
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllFeedbackResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_feedback_by_id_feedbacks__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    change_feedback_status_feedbacks__feedback_id__status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackMessageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    get_feedback_correction_feedbacks__feedback_id__correction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackCorrectionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
    change_feedback_correction_feedbacks__feedback_id__correction_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCorrectionRequst"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackCorrectionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Type */
                        type: string;
                        /** Title */
                        title: string;
                        /** Status */
                        status: number;
                        /** Detail */
                        detail: string;
                        /** Validation Problems */
                        validation_problems: string[] | null;
                    };
                };
            };
        };
    };
}
